# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: cimg/openjdk:20.0.1-node
              environment:
                # Customize the JVM maximum heap limit
                MAVEN_OPTS: -Xmx3200m

            - image: cimg/mysql:8.0
              environment:
                  # Customize the MYSQL Properties
                  DB_ROOT_USER: root
                  DB_DRIVER: com.mysql.cj.jdbc.Driver
                  DB_PASS: ""
                  RESUME_DB_URL: jdbc:mysql://localhost:3306/resume
                  MYSQL_ALLOW_EMPTY_PASSWORD: yes
                  MYSQL_ROOT_PASSWORD: ''

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/postgres:9.4

        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "pom.xml" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: mvn dependency:go-offline

            - save_cache:
                  paths:
                      - ~/.m2
                  key: v1-dependencies-{{ checksum "pom.xml" }}

            # run tests!
            - run: mvn integration-test